version: 2

updates:
  - package-ecosystem: "docker"  # Specify Docker as the package manager
    directory: "/"  # Directory where the Dockerfile is located, usually the project root
    schedule:
      interval: "hourly"  # Use predefined interval instead of cron
