name: Deploy to Vercel

on:
  push:
    branches:
      - main  # 你要部署的分支
      - dev  # 你要部署的分支
      - feature/*  # 你要部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 安裝 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 使用 pnpm 安裝依賴，並且不使用 lock 文件
      - name: Install Dependencies
        run: pnpm install --no-lockfile

      # Debug: 確保 Secrets 被正確讀取
      - name: Debug Environment Variables
        run: |
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}"
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v25
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
          vercel-args: "--prod"  # 部署到正式環境