name: Docker Cleanup

# Manual trigger
on:
  workflow_dispatch: 

jobs:
  clean-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: List all Docker images
      id: images
      run: |
        # List all images and filter out images named base.image
        docker images --format '{{.Repository}}:{{.Tag}} {{.CreatedAt}}' | grep "base.image" > images.txt
        # List all images except base.image and delete them
        docker images --format '{{.Repository}}:{{.Tag}}' | grep -v "base.image" | xargs -I {} docker rmi {}

    - name: Check if there are any base.image images
      run: |
        if [ ! -s images.txt ]; then
          echo "No matching images found"
          exit 0
        fi

    - name: Keep the latest 5 base.image images
      run: |
        # Sort and keep the top 5 most recently created base.image images
        top_images=$(cat images.txt | sort -k2 -r | head -n 5)
        echo "Retained images:"
        echo "$top_images"
        
        # Get the names of the retained images and delete the others
        all_images=$(cat images.txt)
        for image in $all_images; do
          if ! echo "$top_images" | grep -q "$image"; then
            docker rmi $image || true
          fi
        done
